bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}
server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  main:
    allow-circular-references: true

rabbit:
  queues:
    - "GROUPS_QUEUE"
    - "SCHEDULE"
    - "NOTIFICATION"
    - "ANSWER_TEXT"