bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}
server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  main:
    allow-circular-references: true

rabbit:
  queues:
    groups: "GROUPS_QUEUE"
    schedule: "SCHEDULE"
    notification: "NOTIFICATION"
    answer-text: "ANSWER_TEXT"